dist: bionic
language: csharp
mono: none
dotnet: 2.2.103
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/verbose/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/verbose/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
script:
 - dotnet restore
 - dotnet build
 - find . -maxdepth 2 -name “*Test.csproj” -type f | xargs dotnet test

 notifications:
  email:
    recipients:
      - 1061832@ucn.dk
      - 1061832@ucn.dk
      - 1061832@ucn.dk
    on_success: always # default: change
    on_failure: always # default: always
 